# jake pauls
# https://jakepauls.dev
# https://github.com/jake-pauls

# Only allow the following prompt options
format = """
$username\
$hostname\
$directory\
$git_branch\
$python\
$character\
"""

# Print new line at the start of prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[username]
show_always = true
style_user = "bold yellow"
format = "[\\[](bold blue)[$user]($style)[@](dimmed cyan)"

[hostname]
ssh_only = false
style = "bold green"
format = "[$hostname]($style)"
disabled = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold blue)"

[directory]
style = "cyan"
truncation_length = 1
truncate_to_repo = true
format = "[ $path]($style)[\\]](bold blue) "

[git_branch]
style = ""
symbol = "🌿 "
truncation_length = 32
truncation_symbol = ""

# Working, just not in use at the moment
[git_state]
rebase = "[📌 REBASING](bold blue)"
merge = "[🚨 MERGING](bold yellow)"
revert = "[🔥 REVERTING](bold yellow)"
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
untracked = "🍃"
modified = "🎉${count}"
staged = "📍${count}"
renamed = "📝${count}"
deleted = "❌${count}"
style = ""

[nodejs]
format = "[ $version ](bold green)"

[python]
symbol = "🐍 "
python_binary = ['./venv/bin/python']
format = "[$symbol($output$virtualenv )]($style)"

[custom.npm]
description = "Version for npm in the working directory"
command = "npm --version"
files = ["package-lock.json"]
symbol = "🐸 v"
style = "bold green"
format = "[$symbol($output )]($style)"

[custom.yarn]
description = "Version for yarn in the working directory"
command = "yarn --version"
files = ["yarn.lock"]
symbol = "🐱 v"
style = "bold blue"
format = "[$symbol($output )]($style)"
