# Jake Pauls
# https://jacobpauls.dev
# https://github.com/jacob-pauls

# Print new line at the start of prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = "[⚡](bold yellow)"
error_symbol = "[⚡](bold red)"
vicmd_symbol = "[⚡](bold green)"

[directory]
style = "bold green"
truncation_length = 1
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
style = "bold cyan"
symbol = "🌿 "
truncation_length = 10
truncation_symbol = ""

[git_state]
rebase = "[📌 REBASING](bold blue)"
merge = "[🚨 MERGING](bold yellow)"
revert = "[🔥 REVERTING](bold yellow)"
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "💥"
ahead = "ᐃ"
behind = "ᐁ"
diverged = "⇕"
untracked = "🍃"
stashed = "🍞"
modified = "🎉${count}"
staged = "📍${count}"
renamed = "📝${count}"
deleted = "❌${count}"
style = ""

[custom.yarn]
description = "Version for yarn in the working directory"
files = ["yarn.lock"]
symbol = "yarn "
style = "bold blue"
format = "v[$output]($style)"
